const journey: string[] = [
  "start",
  "do",
  "happiness",
  "north-star",
  "goals",
  "reality-to-obvious",
  "maps",
  "cloudy-future",
  "pivot",
  "silos",
  "guard-rails",
  "how-to-contribute",
  "things-change-do",
  "trunk",
  "tensions",
  "me-to-org",
  "todo",
  "delivery-lead",
  "product-lead",
  "technical-lead",
  "worth-knowing",
  "turn-up-the-good",
  "delete-something",
  "wip",
  "wrap",
];
export default journey;
